{"name": "test_negative_assert", "status": "failed", "statusDetails": {"message": "AssertionError: assert 9 == 10", "trace": "self = <tests.test_base_assertion.TestBase object at 0x7f49e9b68af0>\n\n    @pytest.mark.smoke\n    def test_negative_assert(self) -> None:\n        a = 9\n        b = 10\n        debug(f\"a = {a}, but b = {b}\")\n        warning(\"WARNING: Negative assertion\")\n        error(\"ERROR: Negative assertion\")\n>       assert a == b\nE       assert 9 == 10\n\ntests/test_base_assertion.py:18: AssertionError"}, "attachments": [{"name": "log", "source": "2ce324ac-7a0d-4bb1-9e46-d32564217b4d-attachment.txt", "type": "text/plain"}], "start": 1749641309907, "stop": 1749641309908, "uuid": "0c00fba8-c5c4-4265-a4d9-2c3edd033439", "historyId": "c129779ea6db712680d1c8f7923c5962", "testCaseId": "c129779ea6db712680d1c8f7923c5962", "fullName": "tests.test_base_assertion.TestBase#test_negative_assert", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_base_assertion"}, {"name": "subSuite", "value": "TestBase"}, {"name": "host", "value": "fv-az1390-417"}, {"name": "thread", "value": "2943-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_base_assertion"}]}