{"name": "test_negative_assert", "status": "failed", "statusDetails": {"message": "AssertionError: assert 9 == 10", "trace": "self = <tests.test_base_assertion.TestBase object at 0x7f98f67793f0>\n\n    @pytest.mark.smoke_\n    def test_negative_assert(self) -> None:\n        a = 9\n        b = 10\n        debug(f\"a = {a}, but b = {b}\")\n        warning(\"WARNING: Negative assertion\")\n        error(\"ERROR: Negative assertion\")\n>       assert a == b\nE       assert 9 == 10\n\ntests/test_base_assertion.py:18: AssertionError"}, "attachments": [{"name": "log", "source": "58f1413d-3d42-40ea-9fea-9402086356bb-attachment.txt", "type": "text/plain"}], "start": 1749634765172, "stop": 1749634765173, "uuid": "95ee09ad-2f90-400a-8e42-34643634a6d0", "historyId": "c129779ea6db712680d1c8f7923c5962", "testCaseId": "c129779ea6db712680d1c8f7923c5962", "fullName": "tests.test_base_assertion.TestBase#test_negative_assert", "labels": [{"name": "tag", "value": "smoke_"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_base_assertion"}, {"name": "subSuite", "value": "TestBase"}, {"name": "host", "value": "fv-az1369-166"}, {"name": "thread", "value": "3040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_base_assertion"}]}