{"name": "test_negative_assert", "status": "failed", "statusDetails": {"message": "AssertionError: assert 9 == 10", "trace": "self = <tests.test_base_assertion.TestBase object at 0x7fdf3a8175e0>\n\n    @pytest.mark.smoke_\n    def test_negative_assert(self) -> None:\n        a = 9\n        b = 10\n        debug(f\"a = {a}, but b = {b}\")\n        warning(\"WARNING: Negative assertion\")\n        error(\"ERROR: Negative assertion\")\n>       assert a == b\nE       assert 9 == 10\n\ntests/test_base_assertion.py:18: AssertionError"}, "attachments": [{"name": "log", "source": "0df2c6bd-c0a2-428f-b10e-47c880cb1ccd-attachment.txt", "type": "text/plain"}], "start": 1749634561186, "stop": 1749634561186, "uuid": "c0235324-b6d0-453d-a68a-11899d9441b3", "historyId": "c129779ea6db712680d1c8f7923c5962", "testCaseId": "c129779ea6db712680d1c8f7923c5962", "fullName": "tests.test_base_assertion.TestBase#test_negative_assert", "labels": [{"name": "tag", "value": "smoke_"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_base_assertion"}, {"name": "subSuite", "value": "TestBase"}, {"name": "host", "value": "fv-az1283-830"}, {"name": "thread", "value": "2983-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_base_assertion"}]}