{"name": "test_negative_assert", "status": "failed", "statusDetails": {"message": "AssertionError: assert 9 == 10", "trace": "self = <tests.test_base_assertion.TestBase object at 0x7fed987271c0>\n\n    @pytest.mark.smoke\n    def test_negative_assert(self) -> None:\n        a = 9\n        b = 10\n        debug(f\"a = {a}, but b = {b}\")\n        warning(\"WARNING: Negative assertion\")\n        error(\"ERROR: Negative assertion\")\n>       assert a == b\nE       assert 9 == 10\n\ntests/test_base_assertion.py:18: AssertionError"}, "attachments": [{"name": "log", "source": "93fd4482-5448-451f-9705-8dddf16942a6-attachment.txt", "type": "text/plain"}], "start": 1749641893656, "stop": 1749641893657, "uuid": "cdf9dad6-c50a-4d3d-8712-9b517210391a", "historyId": "c129779ea6db712680d1c8f7923c5962", "testCaseId": "c129779ea6db712680d1c8f7923c5962", "fullName": "tests.test_base_assertion.TestBase#test_negative_assert", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_base_assertion"}, {"name": "subSuite", "value": "TestBase"}, {"name": "host", "value": "fv-az1046-954"}, {"name": "thread", "value": "2926-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_base_assertion"}]}